# syntax=docker/dockerfile:1

FROM golang:1.21.5-alpine

RUN apk add --no-cache gcc
RUN apk add --no-cache musl-dev

RUN addgroup -S mercari && adduser -S trainee -G mercari

WORKDIR /app

COPY . /app/
RUN mv db /db && chown -R trainee:mercari /db

RUN go mod tidy

EXPOSE 9000

CMD ["go", "run", "/app/app/main.go"]
