FROM alpine

# WORKDIR /go

RUN addgroup -S mercari && adduser -S trainee -G mercari
# RUN chown -R trainee:mercari /path/to/db
RUN apk add --no-cache go

# COPY go.mod go.sum ./
# RUN go mod download
# COPY *.go ./app

USER trainee

CMD ["go", "version"]
