# syntax=docker/dockerfile:1

FROM golang:1.21.5-alpine

RUN apk add --no-cache gcc
RUN apk add --no-cache musl-dev

RUN addgroup -S mercari && adduser -S trainee -G mercari

WORKDIR /app

COPY ./app/ /app/
COPY ./db/ /db/
COPY ./images/ /images/
COPY go.mod /app/
COPY go.sum /app/
RUN chown -R trainee:mercari /db /images

RUN go mod tidy

EXPOSE 9000

CMD ["go", "run", "/app/main.go"]
